name: Expo iOS Prebuild + Build

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install global Expo CLI
        run: npm install -g expo-cli

      - name: Install project dependencies
        run: npm install

      - name: Run expo prebuild for iOS
        run: npx expo prebuild --platform ios

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: List Xcode schemes
        run: xcodebuild -workspace ios/texasholdemhandevaluator.xcworkspace -list

      - name: Build Xcode archive (.xcarchive)
        run: |
          xcodebuild \
            -workspace ios/texasholdemhandevaluator.xcworkspace \
            -scheme texasholdemhandevaluator \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/texasholdemhandevaluator.xcarchive \
            archive

      - name: Export .ipa
        run: |
          xcodebuild -exportArchive \
            -archivePath build/texasholdemhandevaluator.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ExportedIPA

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: texasholdemhand.ipa
          path: build/ExportedIPA/*.ipa
